name: Draft a release

on:
  push:
    tags:
      - "*"

jobs:
  draft-a-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - uses: trstringer/manual-approval@v1
      #   with:
      #     secret: ${{ github.TOKEN }}
      #     approvers: ${{ steps.get_data.outputs.approvers }}
      #     minimum-approvals: 2
      #     issue-title: 'Release opensearch-cluster-cdk : ${{ steps.get_data.outputs.version }}'
      #     issue-body: "Please approve or deny the release of opensearch-cluster-cdk. **VERSION**: ${{ steps.get_data.outputs.version }} **TAG**: ${{ github.ref_name }}  **COMMIT**: ${{ github.sha }}"
      #     exclude-workflow-initiator-as-approver: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
